services:
  cli:
    build:
      dockerfile: "Dockerfile.dev"
    networks:
      - localblockchain
    environment:
      - NODE_ENV=dev
    entrypoint: ["npm", "run","dev"]
    depends_on:
      - anvil

  anvil:
    image:  ghcr.io/foundry-rs/foundry:latest
    ports:
      - "8545:8545"
    networks:
      - "localblockchain"
    environment:
      - ANVIL_IP_ADDR=0.0.0.0
    entrypoint: ["anvil"]
networks:
  localblockchain: