export type Screens =
	| "auth"
	| "generate-wallet"
	| "import-wallet"
	| "login"
	| "reset"
	| "main-menu"
	| "copy-to-clipboard"
	| "switch-account"
	| "logout"
	| "qr-code"
	| "networks-menu"
	| "switch-network"
	| "add-network"
	| "send-transaction";